FROM python:3-alpine

WORKDIR /app

COPY MeteoServer.py requirements.txt ./
COPY MeteoFranceInterface ./MeteoFranceInterface
COPY RedisHandler ./RedisHandler

RUN pip install -r requirements.txt

#No need to expose anymore as we have ony internal usage from NGINX
#EXPOSE 4000

CMD ["gunicorn", "--log-level", "info", "--access-logfile", "-", "-b", "0.0.0.0:4000", "MeteoServer:app"]
