FROM python:3-slim

WORKDIR /app

COPY MeteoRetrieverDaemon.py requirements.txt ./
COPY MeteoFranceInterface ./MeteoFranceInterface
COPY RedisHandler ./RedisHandler

RUN pip install -r requirements.txt

CMD ["python3", "MeteoRetrieverDaemon.py"]
